image:
  repository: jc21/nginx-proxy-manager
  pullPolicy: IfNotPresent
  tag: 2.11.1
resources:
  limits:
    cpu: 2000m
    memory: 4Gi
npmConfig:
  additionalEnvs: []
npmNetwork:
  webPort: 9081
  httpPort: 9080
  httpsPort: 9443
npmID:
  user: 568
  group: 568
npmStorage:
  data:
    type: ixVolume
    datasetName: data
  certs:
    type: ixVolume
    datasetName: certs
  opt:
    type: ixVolume
    datasetName: opt
notes:
  custom: |
    Default credentials:
    -  username: admin@example.com
    -  password: changeme
